In [1]:
import torch


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [12]:
x = torch.arange(24).view(4, 6)
print(x)
m = torch.tensor([[0, 2], [0, 1]])
print(m)
m = m.view(-1)
print(m)
x = torch.index_select(x, 0, m)
print(x)


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([[0, 2],
        [0, 1]])
tensor([0, 2, 0, 1])
tensor([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
